# render.yaml
# Διαμόρφωση για ανάπτυξη στο Render.com

services:
  - type: web
    name: crypto-forecast-app-el
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn web_dashboard:app"
    # Η θύρα 5000 είναι η προεπιλεγμένη για το Flask
    port: 5000
    # Αυτόματη ανάπτυξη από το GitHub κάθε φορά που γίνεται push
    autoDeploy: true
    # Κλάση για δωρεάν χρήση (ή 'standard' για παραγωγή)
    plan: free
    # Έλεγχος υγείας για να διασφαλιστεί ότι η εφαρμογή τρέχει
    healthCheckPath: /health
    # Προσθήκη έκδοσης Python για συμβατότητα
    # ΣΗΜΑΝΤΙΚΟ: Η ενότητα envVars πρέπει να έχει την ίδια εσοχή με τα buildCommand, startCommand κ.λπ.
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12 # Επιλέξτε 3.10.12, 3.9.18 ή 3.11.9. Το 3.10.12 είναι μια καλή επιλογή.
